### ISSUE TITLE
analisis database

### ISSUE THREAD

**Issue by ryancode-commit** [Narai-Coder-Projects/web-revamp-naraicoder-be#1]

**Comment by ryancode-commit** [comment]
analysis database sudah selesai,  tolong di cek kak

**Comment by ryancode-commit** [comment]
ini link nya [drawio](https://app.diagrams.net/?src=about#HNarai-Coder-Projects%2Fweb-revamp-naraicoder-be%2F1-analisis-database%2FUntitled%20Diagram.drawio#%7B%22pageId%22%3A%22R2lEEEUBdFMjLlhIrx00%22%7D)

**Comment by rholanddeo** [comment]
oke aing bikin migrasinya yee
